# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }} we are going to create Zip file for your release on Moodle :)"
  zip:
    runs-on: ubuntu-latest
    
    steps:
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          files: ADS-Praktikum/Praktikas/ADS-Praktikum01/src/main/java/Praktikum_01_Code/
          dest: ADS-Praktikum01-archiluc.zip

