# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  zip:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Zip Folder ADS-Praktikum and create Release Folder
        run: |
          zip -r -D ADS-Praktikum01-archiluc.zip ./Praktikas/ADS-Praktikum01/src/main/java/Praktikum_01_Code/
          zip -r -D ADS-Praktikum02-archiluc.zip ./Praktikas/ADS-Praktikum02/src/main/java/Praktikum_02_Code/
          zip -r -D ADS-Praktikum03-archiluc.zip ./Praktikas/ADS-Praktikum03/src/main/java/Praktikum_03_Code/
          zip -r -D ADS-Praktikum04-archiluc.zip ./Praktikas/ADS-Praktikum04/src/main/java/Praktikum_04_Code/
          zip -r -D ADS-Praktikum05-archiluc.zip ./Praktikas/ADS-Praktikum05/src/main/java/Praktikum_05_Code/
          zip -r -D ADS-Praktikum06-archiluc.zip ./Praktikas/ADS-Praktikum06/src/main/java/Praktikum_06_Code/
          zip -r -D ADS-Praktikum07-archiluc.zip ./Praktikas/ADS-Praktikum07/src/main/java/Praktikum_07_Code/
          zip -r -D ADS-Praktikum08-archiluc.zip ./Praktikas/ADS-Praktikum08/src/main/java/Praktikum_08_Code/
          zip -r -D ADS-Praktikum09-archiluc.zip ./Praktikas/ADS-Praktikum09/src/main/java/Praktikum_09_Code/
          zip -r -D ADS-Praktikum10-archiluc.zip ./Praktikas/ADS-Praktikum10/src/main/java/Praktikum_10_Code/
          zip -r -D ADS-Praktikum11-archiluc.zip ./Praktikas/ADS-Praktikum11/src/main/java/Praktikum_11_Code/
          zip -r -D ADS-Praktikum12-archiluc.zip ./Praktikas/ADS-Praktikum12/src/main/java/Praktikum_12_Code/
          zip -r -D ADS-Praktikum13-archiluc.zip ./Praktikas/ADS-Praktikum13/src/main/java/Praktikum_13_Code/
      - name: Put ADS01 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum01-archiluc.zip
      - name: Put ADS02 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum02-archiluc.zip
      - name: Put ADS03 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum03-archiluc.zip
      - name: Put ADS04 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum04-archiluc.zip
      - name: Put ADS05 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum05-archiluc.zip
      - name: Put ADS06 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum06-archiluc.zip
      - name: Put ADS07 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum07-archiluc.zip
      - name: Put ADS08 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum08-archiluc.zip
      - name: Put ADS09 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum09-archiluc.zip
      - name: Put ADS10 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum10-archiluc.zip
      - name: Put ADS11 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum11-archiluc.zip
      - name: Put ADS12 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum12-archiluc.zip
      - name: Put ADS13 to Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ADS-Praktikum13-archiluc.zip
